data:
  raw_path: "data/raw"
  processed_path: "data/processed"
  models_path: "data/models"

model:
  seq_length: 30
  embedding_dim: 64
  hidden_dim: 128
  learning_rate: 0.001
  epochs: 30

system:
  # CHANGE THESE TWO LINES WHEN SWITCHING APPS
  app_name: "pyprobe"   # The ID (used for filenames)
  target_app: 'python3 -c "import json,ssl,sqlite3,subprocess,math,hashlib"' # The actual command
